name: Auto-format (Spotless)
on:
  pull_request:
    paths:
      - 'Minesweeper/**'
      - '**/*.kt'
      - '**/*.kts'

jobs:
  auto-format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Gradle caching
        uses: gradle/actions/setup-gradle@v4

      - name: Run spotlessApply
        working-directory: Minesweeper
        run: ./gradlew :composeApp:spotlessApply

      - name: Commit changes (if any)
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore(spotless): auto-format on CI"
            git push
          else
            echo "No formatting changes."
          fi
