name: Bouncy Bee Web (Wasm) CI

on:
  push:
    paths:
      - 'BouncyBee/composeApp/**'
  pull_request:
    paths:
      - 'BouncyBee/composeApp/**'
  workflow_dispatch:

jobs:
  build:
    name: Build and Deploy Web (Wasm)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Build Web App (Wasm)
        run: ./gradlew :BouncyBee:composeApp:wasmJsBrowserDistribution

      - name: Show Wasm build output
        run: ls -la ./BouncyBee/composeApp/build/dist/wasmJs/productionExecutable

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./BouncyBee/composeApp/build/dist/wasmJs/productionExecutable
          destination_dir: BouncyBee/web
