name: Bouncy Bee Android CI

on:
  push:
    paths:
      - 'composeApp/**'
  pull_request:
    paths:
      - 'composeApp/**'

jobs:
  build:
    name: Build Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew :composeApp:assembleDebug

