name: Bouncy Bee iOS CI

on:
  push:
    paths:
      - 'BouncyBee/composeApp/**'
  pull_request:
    paths:
      - 'BouncyBee/composeApp/**'
  workflow_dispatch:

jobs:
  build:
    name: Build iOS Framework
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./BouncyBee

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Build iOS Framework
        run: ./gradlew :composeApp:linkReleaseFrameworkIosArm64

