name: Bouncy Bee Desktop CI

on:
  push:
    paths:
      - 'BouncyBee/composeApp/**'
  pull_request:
    paths:
      - 'BouncyBee/composeApp/**'
  workflow_dispatch:

jobs:
  build:
    name: Build Desktop (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    defaults:
      run:
        working-directory: ./BouncyBee
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant Gradle permission
        if: runner.os != 'Windows'
        run: chmod +x ./gradlew

      - name: Build Desktop App
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            gradlew.bat :composeApp:packageDistributionForCurrentOS
          else
            ./gradlew :composeApp:packageDistributionForCurrentOS
          fi

