name: Build & Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  changes:
    name: Detect Minesweeper changes
    runs-on: ubuntu-latest
    outputs:
      minesweeper: ${{ steps.filter.outputs.minesweeper }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # tärkeää, paths-filter tarvitsee historian

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            minesweeper:
              - 'Minesweeper/**'
              - 'gradle/**'
              - 'gradlew'
              - 'gradlew.bat'
              - 'gradle.properties'
              - 'settings.gradle*'
              - 'build.gradle*'
              - 'gradle/libs.versions.toml'
              - '.github/workflows/**'

  format:
    name: Spotless Apply & Push
    needs: [changes]
    if: github.event_name == 'workflow_dispatch' || needs.changes.outputs.minesweeper == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Minesweeper
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref }}

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Gradle build cache
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Spotless Apply
        run: ./gradlew :composeApp:spotlessApply

      - name: Commit and push formatting changes
        if: github.event_name == 'pull_request'
        run: |
          cd ..
          if [[ -n "$(git status --short)" ]]; then
            if [[ "${{ github.event.pull_request.head.repo.full_name }}" != "${{ github.repository }}" ]]; then
              echo 'Skipping auto-commit for forked PR.'
            else
              git config user.name "github-actions[bot]"
              git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
              git commit -am "chore: apply spotless formatting"
              git push origin HEAD:${{ github.head_ref }}
            fi
          fi

  quality:
    name: Quality (Spotless Check & Detekt)
    needs: [changes, format]
    if: github.event_name == 'workflow_dispatch' || needs.changes.outputs.minesweeper == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Minesweeper
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref }}

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Gradle build cache
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Spotless Check & Detekt
        run: ./gradlew :composeApp:spotlessCheck :composeApp:detekt

      - name: Upload Detekt reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: detekt-reports
          path: |
            Minesweeper/composeApp/build/reports/detekt/*.html
            Minesweeper/composeApp/build/reports/detekt/*.xml
          if-no-files-found: warn

  tests:
    name: JVM Tests & Coverage
    needs: [changes, format, quality]
    if: github.event_name == 'workflow_dispatch' || needs.changes.outputs.minesweeper == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Minesweeper
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref }}

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Gradle build cache
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: JVM tests & Kover reports
        run: ./gradlew :composeApp:test :composeApp:koverXmlReport :composeApp:koverHtmlReport

      - name: Upload Kover coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: kover-reports
          path: |
            Minesweeper/composeApp/build/reports/kover/html
            Minesweeper/composeApp/build/reports/kover/xml
          if-no-files-found: warn

  android:
    name: Android (assembleDebug)
    needs: [changes, format, quality, tests]
    if: github.event_name == 'workflow_dispatch' || needs.changes.outputs.minesweeper == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Minesweeper
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref }}

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Android SDK (accept licenses)
        uses: android-actions/setup-android@v3

      - name: Gradle build cache
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build debug APK
        run: ./gradlew :composeApp:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk-debug
          path: Minesweeper/composeApp/build/outputs/apk/debug/*.apk
          if-no-files-found: warn

  desktop:
    name: Desktop (uber-jar)
    needs: [changes, format, quality, tests]
    if: github.event_name == 'workflow_dispatch' || needs.changes.outputs.minesweeper == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Minesweeper
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref }}

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Gradle build cache
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build uber-jar
        run: ./gradlew :composeApp:packageReleaseUberJarForCurrentOS

      - name: Upload Desktop JAR
        uses: actions/upload-artifact@v4
        with:
          name: desktop-uber-jar
          path: Minesweeper/composeApp/build/compose/jars/*.jar
          if-no-files-found: warn

  wasm:
    name: Wasm (production distribution)
    needs: [changes, format, quality, tests]
    if: github.event_name == 'workflow_dispatch' || needs.changes.outputs.minesweeper == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Minesweeper
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref }}

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Gradle build cache
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build wasm distribution
        run: ./gradlew :composeApp:wasmJsBrowserDistribution

      - name: Upload Wasm dist
        uses: actions/upload-artifact@v4
        with:
          name: wasm-dist
          path: Minesweeper/composeApp/build/dist/wasmJs/productionExecutable/**
          if-no-files-found: warn
