# Minimal Detekt config – extend later
build:
  maxIssues: 0
config:
  validation: true
processors:
  active: true

# Common Compose/KMP relaxations; tighten later when code stabilizes
style:
  MagicNumber:
    active: false
  ReturnCount:
    active: true
    max: 5

complexity:
  LongMethod:
    active: false
  LongParameterList:
    active: false
  TooManyFunctions:
    active: false
  CyclomaticComplexMethod:
    active: true
    threshold: 25
  NestedBlockDepth:
    active: true
    threshold: 4

naming:
  # Package and class rules stay enabled; adjust as needed
  FunctionNaming:
    active: true
    # Keep PascalCase allowance for @Composable handled by ktlint; detekt focuses on other funcs
    ignoreAnnotated:
      - Composable

  MatchingDeclarationName:
    active: true
    excludes:
      - '**/Platform.*.kt'


